routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.frontpage',['slug'=>'/']);
});
Auth::routes();
Route::get('/admin', function(){
    return view('admin.dashboard');
})->name('admin')->middleware('auth')->middleware(['role:administrator']);
Route::get('/home', function(){
    return view('home');
});
//Login
Route::post('loginsite','HomeController@check');

//Group admin
Route::group(['prefix' => 'admin','as'=>'admin.','middleware' => ['auth','role:administrator']], function () {

//    Display users
    Route::get('users', function () {
        $roles = App\User::get_roles();
        return view('admin.users.users',['roles'=>$roles]);
    })->name('users');

//    Display profile user
    Route::get('profile', function () {
        $roles = App\User::get_roles();
        return view('admin.users.profile',['roles'=>$roles]);
    })->name('profile');

    //    Display profile user other
    Route::get('user/{id}/view', function ($id) {
        $roles = App\User::get_roles();
        $user = App\User::getUserByID($id);
        return view('admin.users.user_view',['user'=>$user,'roles'=>$roles]);
    })->name('user_view');

    //    Edit profile user other
    Route::get('user/{id}/edit', function ($id) {
        return view('admin.users.user_edit',['user_id'=>$id]);
    })->name('user_edit');
// change passord
    Route::post('change_password', 'auth\UpdateUser@ChangePassword');
    // update field main user
    Route::post('update_userinfo', 'auth\UpdateUser@UpdateUserInfo');
    // ajax delete user
    Route::post('detele_user', 'auth\UpdateUser@DeleteUser');

    // Posts
    Route::get('posts', function () {
        return view('admin.posts.posts');
    })->name('posts');
    // add new story
    Route::get('add-post', function () {
        return view('admin.posts.addnew_post');
    })->name('add-post');

    // edit story
    Route::get('post/{id}/edit', function ($id) {
        return view('admin.posts.edit_post',['post_id'=>$id]);
    })->name('edit_post');
    // add story
    Route::post('add_post', 'ControllerPosts@add_post');
    //save story
    Route::post('save_post', 'ControllerPosts@save_post');

    // ajax story & all
    Route::post('admin_ajax', 'ControllerAjax@admin_ajax');

    // Media
    Route::get('media', function () {
        return view('admin.media.media');
    })->name('media');
    
    Route::get('media/list', function () {
        return view('admin.media.media_list');
    })->name('media_list');

    Route::post('upload','ControllerMedia@doUpload');

    //products
    Route::get('products', function () {
        return view('admin.products.products');
    })->name('products');

    // product categories
    Route::get('product_categories', function () {
        return view('admin.products.product_categories');
    })->name('product_categories');
    // add product categories
    Route::POST('add_product_category', 'ControllerProduct@add_product_category');

    // add new product
    Route::get('add-product', function () {
        return view('admin.products.add-product');
    })->name('add-product');

    Route::post('add_product','ControllerProduct@add_product');

    // edit product
    Route::get('product/{id}/edit', function ($id) {
        return view('admin.products.edit-product',['product_id'=>$id]);
    })->name('edit-product');

    Route::post('edit_product','ControllerProduct@save_product');

    //Orders
    Route::get('orders', function () {
        return view('admin.order.orders');
    })->name('orders');

    // edit product
    Route::get('order/{id}/view', function ($id) {
        return view('admin.order.view-order',['order_id'=>$id]);
    })->name('view-order');

    // edit new orders
    Route::get('order/{id}/edit', function ($id) {
        return view('admin.order.edit-order',['order_id'=>$id]);
    })->name('edit-order');
    // edit order
    Route::post('edit_order','ControllerOrders@save_order');

    // FAQ setting

    // edit new orders
    Route::get('faq', function () {
        return view('admin.widgets.faq');
    })->name('faq');
    // update FAQ
    Route::post('save_faq','ControllerOptions@save_faq');

    // Contact Form
    Route::get('contact-form', function () {
        return view('admin.widgets.contact-form');
    })->name('contact-form');

    Route::get('contact-form/{slug}', function ($slug) {
        return view('admin.widgets.ctf-detail',['slug'=>$slug]);
    })->name('contact-form-detail');


    // Data Form
    Route::get('data-form', function () {
        return view('admin.maketing.data-form');
    })->name('data-form');

    // add data form
    Route::get('add-data-form', function () {
        return view('admin.maketing.add_data-form');
    })->name('add-data-form');

    // edit data form
    Route::get('data-form/{id}/edit', function ($id) {
        return view('admin.maketing.edit_data-form',['id'=>$id]);
    })->name('edit-data-form');



    // System Settings
    Route::get('system-settings', function () {
        return view('admin.system-settings');
    })->name('system-settings');
});


// main pages
// Stories page
Route::get('/posts', function(){
    return view('frontend.posts',['slug'=>'posts']);
});

// Story detail
Route::get('/post/{slug}', function($slug){
    return view('frontend.single-post',['slug'=>$slug]);
});

//Add story comments
Route::post('/post/{slug}','ControllerStories@add_post_comment');

// Media page
Route::get('/media', function(){
    return view('frontend.media',['slug'=>'media']);
});

// FAQ page
Route::get('/faq', function(){
    return view('frontend.faq',['slug'=>'faq']);
});

// About page
Route::get('/about', function(){
    return view('frontend.about',['slug'=>'about']);
});

// Shop page
Route::get('/gift-shop', function(){
    return view('frontend.shop',['slug'=>'gift-shop']);
})->name('shops');

// Story detail
Route::get('/product/{slug}', function($slug){
    return view('frontend.single-product',['slug'=>$slug]);
});


// My account
Route::get('/my-account', function(){
    return view('frontend.account',['slug'=>'account']);
})->name('my-account')->middleware('auth');

// ajax not admin all
Route::post('nopriv_ajax', 'ControllerAjax@admin_ajax')->name('nopriv_ajax')->middleware('auth');
Route::post('nopriv_upload','ControllerMedia@doUpload')->name('nopriv_ajax')->middleware('auth');


// My cart
Route::get('/cart', function(){
    return view('frontend.cart',['slug'=>'cart']);
})->name('cart');

app/Media.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Media extends Model
{
    public $table = 'media';
    public static function get_media($where=''){
        if($where){
            $medias = DB::table('media')->where('type','LIKE', $where.'%')->orderBy('id', 'desc')->paginate(12);
        }else{
            $medias = DB::table('media')->orderBy('id', 'desc')->paginate(12);
        }
        return $medias;
    }

    public static function get_media_detail($id){
        $media = DB::table('media')->where('id', $id)->first();
        return $media;
    }
}

resources/views/admin/media/media.blade.php
@extends('admin.media.media_layout')
@section('content')
    <?php
            $type = (isset($_GET['type']))?$_GET['type']:'';
            if($type){
                $medias = App\Media::get_media($_GET['type']);
            }else{
                $medias = App\Media::get_media();
            }
    ?>
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">
                        Media
                        <a class="btn btn-primary" data-toggle="collapse" href="#form-upload-media" role="button" aria-expanded="false" aria-controls="form-upload-media">
                            Upload
                        </a>
                    </h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Home</a></li>
                        <li class="breadcrumb-item active">Media manage</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <div class="card-title">
                                List Media
                            </div>
                        </div>
                        <div class="card-body">
                            <div>
                                <div id="form-upload-media" class="collapse mb-5 mt-2">
                                    <form action="{{ url('admin/upload') }}" enctype="multipart/form-data" method="POST">
                                        {{ csrf_field() }}
                                        <input type="file" name="UploadMedia" required="true">
                                        <br/>
                                        <button type="button" class="btn-button-upload">Upload Media</button>
                                    </form>
                                </div>

                                <div class="filter-media mb-5">
                                    <div class="text-left">
                                        <div class="btn-group">
                                            <a class="btn btn-default" href="{{ route('admin.media_list') }}"> <i class="fas fa-th-list" style="font-size: 20px;"></i> </a>
                                            <a class="btn btn-default active" href="{{ route('admin.media') }}" data-sortDesc> <i class="fas fa-th" style="font-size: 20px;"></i> </a>
                                        </div>
                                        <select class="custom-select" name="type" style="width: auto;">
                                            @foreach(select_type_media() as $key=> $value)
                                                <option value="{{ $key }}" {{ ($key == $type)?'selected':'' }}> {{ $value }} </option>
                                            @endforeach
                                        </select>
                                        <button type="button" id="apply-filter" class="btn btn-primary">Apply</button>
                                    </div>
                                </div>
                            </div>

                            <div>
                                <div id="grid-medias" class="filter-container p-0 row">
                                    @if (count($medias) > 0)
                                        @foreach ($medias as $media)
                                    <div class="item-media filtr-item mb-5 col-sm-2">
                                        <div class="link"  style="background-image: url('{{ show_img_media($media->type,$media->link)}}');">
                                                <img src="{{ url('uploads/use/plus2.png') }}" class="responsive" data-ID="{{ $media->id }}" onclick="setup_media_byjson('{{ json_encode($media) }}')" data-toggle="modal" data-target="#MediaModal" data-type="{{ get_type_media($media->type) }}" data-size="{{ get_size_media($media->path) }}" />
                                            @if( get_type_media($media->type) != 'image')
                                                <span class="name-media d-block">{{ get_name_media( $media->path ) }}</span>
                                            @endif
                                        </div>
                                    </div>
                                        @endforeach
                                    @endif
                                </div>

                            </div>
                            <nav aria-label="Page navigation example">
                                <ul class="pagination">
                                    <li class="page-item"><a class="page-link" href="{{ $medias->previousPageUrl() }}">Previous</a></li>
                                    <li class="page-item"><span class="page-link">{{ $medias->currentPage() }}</span></li>
                                    <li class="page-item"><a class="page-link" href="{{ $medias->nextPageUrl() }}">Next</a></li>
                                </ul>
                            </nav>

                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/media/media_list.blade.php
@extends('admin.media.media_layout')
@section('content')
    <?php
    $type = (isset($_GET['type']))?$_GET['type']:'';
    if($type){
        $medias = App\Media::get_media($_GET['type']);
    }else{
        $medias = App\Media::get_media();
    }
    ?>
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">
                        Media
                        <a class="btn btn-primary" data-toggle="collapse" href="#form-upload-media" role="button" aria-expanded="false" aria-controls="form-upload-media">
                            Upload
                        </a>
                    </h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Home</a></li>
                        <li class="breadcrumb-item active">Media manage</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <div class="card-title">
                                List Media
                            </div>
                        </div>
                        <div class="card-body">
                            <div>
                                <div id="form-upload-media" class="collapse mb-5 mt-2">
                                    <form action="{{ url('admin/upload') }}" enctype="multipart/form-data" method="POST">
                                        {{ csrf_field() }}
                                        <input type="file" name="UploadMedia" data-type="list" required="true">
                                        <br/>
                                        <button type="button" class="btn-button-upload">Upload Media</button>
                                    </form>
                                </div>

                                <div class="filter-media mb-5">
                                    <div class="text-left">
                                        <div class="btn-group">
                                            <a class="btn btn-default active" href="{{ route('admin.media_list') }}"> <i class="fas fa-th-list" style="font-size: 20px;"></i> </a>
                                            <a class="btn btn-default" href="{{ route('admin.media') }}" data-sortDesc> <i class="fas fa-th" style="font-size: 20px;"></i> </a>
                                        </div>
                                        <select class="custom-select" name="type" style="width: auto;">
                                            @foreach(select_type_media() as $key=> $value)
                                                <option value="{{ $key }}" {{ ($key == $type)?'selected':'' }}> {{ $value }} </option>
                                            @endforeach
                                        </select>
                                        <button type="button" id="apply-filter" class="btn btn-primary">Apply</button>
                                    </div>
                                </div>
                            </div>

                            <div>
                                <table class="list-media table table-striped">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Media</th>
                                        <th>Name</th>
                                        <th>Author</th>
                                        <th>Type</th>
                                        <th>Created</th>
                                    </tr>
                                    </thead>
                                    <tbody id="list-medias">
                                    @if (count($medias) > 0)
                                        @foreach ($medias as $media)
                                    <tr>
                                        <td>{{ $media->id }}</td>
                                        <td> <div class="img_featured" style="background-image: url('{{ show_img_media($media->type,$media->link)}}');"></div></td>
                                        <td class="link">
                                                <a data-ID="{{ $media->id }}" onclick="setup_media_byjson('{{ json_encode($media) }}')" data-toggle="modal" data-target="#MediaModal" data-type="{{ get_type_media($media->type) }}" data-size="{{ get_size_media($media->path) }}" >{{ get_name_media( $media->path ) }}</a>
                                        </td>
                                        <td>{{  App\User::getUserByID($media->user_id)->name }}</td>
                                        <td>{{ $media->type }}</td>
                                        <td>{{ $media->created_at }}</td>
                                    </tr>
                                        @endforeach
                                    @endif
                                    </tbody>
                                </table>

                            </div>
                            <nav aria-label="Page navigation example">
                                <ul class="pagination">
                                    <li class="page-item"><a class="page-link" href="{{ $medias->previousPageUrl() }}">Previous</a></li>
                                    <li class="page-item"><span class="page-link">{{ $medias->currentPage() }}</span></li>
                                    <li class="page-item"><a class="page-link" href="{{ $medias->nextPageUrl() }}">Next</a></li>
                                </ul>
                            </nav>

                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection