routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.frontpage',['slug'=>'/']);
});
Auth::routes();
Route::get('/admin', function(){
    return view('admin.dashboard');
})->name('admin')->middleware('auth')->middleware(['role:administrator']);
Route::get('/home', function(){
    return view('home');
});
//Login
Route::post('loginsite','HomeController@check');

//Group admin
Route::group(['prefix' => 'admin','as'=>'admin.','middleware' => ['auth','role:administrator']], function () {

//    Display users
    Route::get('users', function () {
        $roles = App\User::get_roles();
        return view('admin.users.users',['roles'=>$roles]);
    })->name('users');

//    Display profile user
    Route::get('profile', function () {
        $roles = App\User::get_roles();
        return view('admin.users.profile',['roles'=>$roles]);
    })->name('profile');

    //    Display profile user other
    Route::get('user/{id}/view', function ($id) {
        $roles = App\User::get_roles();
        $user = App\User::getUserByID($id);
        return view('admin.users.user_view',['user'=>$user,'roles'=>$roles]);
    })->name('user_view');

    //    Edit profile user other
    Route::get('user/{id}/edit', function ($id) {
        return view('admin.users.user_edit',['user_id'=>$id]);
    })->name('user_edit');
// change passord
    Route::post('change_password', 'auth\UpdateUser@ChangePassword');
    // update field main user
    Route::post('update_userinfo', 'auth\UpdateUser@UpdateUserInfo');
    // ajax delete user
    Route::post('detele_user', 'auth\UpdateUser@DeleteUser');

    // Posts
    Route::get('posts', function () {
        return view('admin.posts.posts');
    })->name('posts');
    // add new story
    Route::get('add-post', function () {
        return view('admin.posts.addnew_post');
    })->name('add-post');

    // edit story
    Route::get('post/{id}/edit', function ($id) {
        return view('admin.posts.edit_post',['post_id'=>$id]);
    })->name('edit_post');
    // add story
    Route::post('add_post', 'ControllerPosts@add_post');
    //save story
    Route::post('save_post', 'ControllerPosts@save_post');

    // ajax story & all
    Route::post('admin_ajax', 'ControllerAjax@admin_ajax');

    // Media
    Route::get('media', function () {
        return view('admin.media.media');
    })->name('media');
    
    Route::get('media/list', function () {
        return view('admin.media.media_list');
    })->name('media_list');

    Route::post('upload','ControllerMedia@doUpload');

    //products
    Route::get('products', function () {
        return view('admin.products.products');
    })->name('products');

    // product categories
    Route::get('product_categories', function () {
        return view('admin.products.product_categories');
    })->name('product_categories');
    // add product categories
    Route::POST('add_product_category', 'ControllerProduct@add_product_category');

    // add new product
    Route::get('add-product', function () {
        return view('admin.products.add-product');
    })->name('add-product');

    Route::post('add_product','ControllerProduct@add_product');

    // edit product
    Route::get('product/{id}/edit', function ($id) {
        return view('admin.products.edit-product',['product_id'=>$id]);
    })->name('edit-product');

    Route::post('edit_product','ControllerProduct@save_product');

    //Orders
    Route::get('orders', function () {
        return view('admin.order.orders');
    })->name('orders');

    // edit product
    Route::get('order/{id}/view', function ($id) {
        return view('admin.order.view-order',['order_id'=>$id]);
    })->name('view-order');

    // edit new orders
    Route::get('order/{id}/edit', function ($id) {
        return view('admin.order.edit-order',['order_id'=>$id]);
    })->name('edit-order');
    // edit order
    Route::post('edit_order','ControllerOrders@save_order');

    // FAQ setting

    // edit new orders
    Route::get('faq', function () {
        return view('admin.widgets.faq');
    })->name('faq');
    // update FAQ
    Route::post('save_faq','ControllerOptions@save_faq');

    // Contact Form
    Route::get('contact-form', function () {
        return view('admin.widgets.contact-form');
    })->name('contact-form');

    Route::get('contact-form/{slug}', function ($slug) {
        return view('admin.widgets.ctf-detail',['slug'=>$slug]);
    })->name('contact-form-detail');


    // Data Form
    Route::get('data-form', function () {
        return view('admin.maketing.data-form');
    })->name('data-form');

    // add data form
    Route::get('add-data-form', function () {
        return view('admin.maketing.add_data-form');
    })->name('add-data-form');

    // edit data form
    Route::get('data-form/{id}/edit', function ($id) {
        return view('admin.maketing.edit_data-form',['id'=>$id]);
    })->name('edit-data-form');



    // System Settings
    Route::get('system-settings', function () {
        return view('admin.system-settings');
    })->name('system-settings');
});


// main pages
// Stories page
Route::get('/posts', function(){
    return view('frontend.posts',['slug'=>'posts']);
});

// Story detail
Route::get('/post/{slug}', function($slug){
    return view('frontend.single-post',['slug'=>$slug]);
});

//Add story comments
Route::post('/post/{slug}','ControllerStories@add_post_comment');

// Media page
Route::get('/media', function(){
    return view('frontend.media',['slug'=>'media']);
});

// FAQ page
Route::get('/faq', function(){
    return view('frontend.faq',['slug'=>'faq']);
});

// About page
Route::get('/about', function(){
    return view('frontend.about',['slug'=>'about']);
});

// Shop page
Route::get('/gift-shop', function(){
    return view('frontend.shop',['slug'=>'gift-shop']);
})->name('shops');

// Story detail
Route::get('/product/{slug}', function($slug){
    return view('frontend.single-product',['slug'=>$slug]);
});


// My account
Route::get('/my-account', function(){
    return view('frontend.account',['slug'=>'account']);
})->name('my-account')->middleware('auth');

// ajax not admin all
Route::post('nopriv_ajax', 'ControllerAjax@admin_ajax')->name('nopriv_ajax')->middleware('auth');
Route::post('nopriv_upload','ControllerMedia@doUpload')->name('nopriv_ajax')->middleware('auth');


// My cart
Route::get('/cart', function(){
    return view('frontend.cart',['slug'=>'cart']);
})->name('cart');

app/Orders.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Orders extends Model
{
    // get all orders
    public static function get_orders($where=''){
        $orders = DB::table('product_orders')->orderByDesc('updated_at')->paginate(12);
        return $orders;
    }
    // get order by id
    public static function get_order($order_id){
        $order = DB::table('product_orders')->where('id',$order_id)->first();
        return $order;
    }

    // status order
    public static function order_status(){
        $order_status = [
            0 => 'Pending payment',
            1 => 'Failed',
            2 => 'Processing',
            3 => 'Completed',
            4 => 'On hold',
            5 => 'Canceled',
            6 => 'Refunded',
            7 => 'Gift',
        ];
        return $order_status;
    }

    // status product
    public static function payment_type(){
        $product_type = [
            0 => 'Cash on delivery',
            1 => 'Direct bank transfer',
            2 => 'PayPal',
        ];
        return $product_type;
    }

    // get meta orders
    public static function get_meta_product_order($order_id,$meta_key,$re=''){
        $order_meta = DB::table('product_order_meta')->where('order_id',$order_id)->where('meta_key',$meta_key)->first();
        if($order_meta)return $order_meta->meta_value ;
        return $re;
    }
    // update meta orders
    public static function update_meta_product_order($order_id,$meta_key,$meta_value){
        $order_meta = self::get_meta_product_order($order_id,$meta_key);
        if($order_meta){
            DB::table('product_order_meta')->where('order_id',$order_id)->where('meta_key',$meta_key)->update(['meta_value'=>$meta_value]);
        }else{
            $order_meta =  self::add_meta_product_order($order_id,$meta_key,$meta_value);
        }
        return $order_meta;
    }

    // get meta orders
    public static function add_meta_product_order($order_id,$meta_key,$meta_value){
        $order_meta = self::get_meta_product_order($order_id,$meta_key);
        if(!$order_meta){
            $data = array(
                'order_id' => $order_id,
                'meta_key' => $meta_key,
                'meta_value' => $meta_value,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            );
            $meta_id = DB::table('product_order_meta')->insertGetId($data);
            return $meta_id;
        }
        return false;
    }

}

resources/views/admin/order/edit-order.blade.php
@extends('admin.order.order_layout')
@section('content')
    <?php
    $user = Auth::user();
    $order = App\Orders::get_order($order_id);
    $order_status = App\Orders::order_status();
    $payment_type = App\Orders::payment_type();

    $customer_bill = App\Orders::get_meta_product_order($order_id,'customer_bill');
    $billing_address = App\Orders::get_meta_product_order($order_id,'billing_address');
    $customer_shipping = App\Orders::get_meta_product_order($order_id,'customer_shipping');
    $shipping_address = App\Orders::get_meta_product_order($order_id,'shipping_address');
    $products = App\Orders::get_meta_product_order($order_id,'products');
    if( isset($products) ){
        $products = display_product_in_order( json_decode($products) );
        $products['tax'] = ($products['subtotal']*$order->tax)/100;
        $products['total'] = $order->shipping + $products['tax'] + $products['subtotal'];
    }
    ?>
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{{ route('admin.orders') }}">Order</a></li>
                        <li class="breadcrumb-item active">Edit Order</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Order #{{ $order_id }}</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body save_order">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Billing Address</label>
                                        <input type="text" name="customer_bill" class="form-control"
                                               placeholder="Customer name" data-title="Customer name"
                                               data-required="false" value="{{ $customer_bill }}">
                                        <span class="um-field-error d-none"></span>
                                        <textarea class="form-control mt-3" name="billing_address" rows="5"
                                                  placeholder="Billing Address" data-title="Billing Address"
                                                  data-required="false">{{ $billing_address }}</textarea>
                                        <span class="um-field-error d-none"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Shipping Address</label>
                                        <input type="text" name="customer_shipping" class="form-control"
                                               placeholder="Customer name" data-title="Customer name"
                                               data-required="true" value="{{ $customer_shipping }}">
                                        <span class="um-field-error d-none"></span>
                                        <textarea class="form-control mt-3" name="shipping_address" rows="5"
                                                  placeholder="Shipping Address" data-title="Shipping Address"
                                                  data-required="true">{{ $shipping_address }}</textarea>
                                        <span class="um-field-error d-none"></span>
                                    </div>
                                </div>
                            </div>
                            <!-- Table row -->
                            <div class="row">
                                <!-- accepted payments column -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Payment type</label>
                                        <select class="form-control select2" name="payment_type"
                                                data-title="Payment Type" data-required="false">
                                            @if($payment_type)
                                                @foreach($payment_type as $key=>$value)
                                                    <option value="{{ $key }}" {{ $key == $order->payment_type ? 'selected':'' }}>{{ $value }}</option>
                                                @endforeach
                                            @endif
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Status</label>
                                        <select class="form-control select2" name="status"
                                                data-title="Status" data-required="false">
                                            @if($order_status)
                                                @foreach($order_status as $key=>$value)
                                                    <option value="{{ $key }}" {{ $key == $order->status ? 'selected':'' }}>{{ $value }}</option>
                                                @endforeach
                                            @endif
                                        </select>
                                    </div>

                                </div>
                                <!-- /.col -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Tax</label>
                                        <input type="number" name="tax" class="form-control" placeholder="Enter tax"
                                               data-title="Tax" data-required="true" min="0" value="{{ $order->tax }}">
                                        <span class="um-field-error d-none"></span>
                                    </div>

                                    <div class="form-group">
                                        <label>Shipping</label>
                                        <input type="number" name="shipping" class="form-control"
                                               placeholder="Enter shipping" data-title="Shipping" data-required="true"
                                               min="0" value="{{ $order->shipping }}">
                                        <span class="um-field-error d-none"></span>
                                    </div>
                                </div>
                                <!-- /.col -->
                            </div>

                            <div class="row">
                                <div class="col-12 table-responsive">
                                    <label>Products</label>
                                    <table class="table table-striped table-hover">
                                        <thead>
                                        <tr>
                                            <th>Qty</th>
                                            <th>Product</th>
                                            <th>Attributes</th>
                                            <th>Subtotal</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @if(isset($products))
                                            {!! $products['html']  !!}
                                        @endif
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.col -->
                            </div>
                            <!-- /.row -->

                            <div class="form-group">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}" data-title="Token"
                                       data-required="false">
                                <input type="hidden" id="action" name="action" value="{{ url('admin/edit_order') }}"
                                       data-title="action" data-required="false"/>
                                <input type="hidden" id="user_id" name="user_id" value="{{ $user->id }}"
                                       data-title="User" data-required="false"/>
                                <input type="hidden" name="id" value="{{ $order_id }}" data-title="ID"
                                       data-required="false"/>
                            </div>
                            <!-- Note -->
                            <div class="form-group">
                                <label>Note</label>
                                <textarea class="form-control" name="note" rows="5" data-title="Note"
                                          data-required="false" placeholder="Note"></textarea>
                            </div>
                            <!-- /.row -->

                        </div>
                    </div>
                    <!-- /.card -->


                </div>
                <!-- right colume-->
                <div class="col-sm-4">
                    <!-- Form Element sizes -->
                    <div class="card card-info">
                        <div class="card-header">
                            <h3 class="card-title">Controls</h3>
                        </div>
                        <div class="card-body">
                            <p class="lead">Date {{ date('m/d/Y') }}</p>

                            <div class="table-responsive">
                                <table class="table">
                                    <tr>
                                        <th style="width:50%">Subtotal:</th>
                                        <td>{{ $products ? format_currency($products['subtotal'],2,'$'):0 }}</td>
                                    </tr>
                                    <tr>
                                        <th>Tax:</th>
                                        <td>{{ $products ? format_currency($products['tax'],2,'$'):0 }}</td>
                                    </tr>
                                    <tr>
                                        <th>Shipping:</th>
                                        <td>{{ $products ? format_currency( $order->shipping ,2,'$'):0 }}</td>
                                    </tr>
                                    <tr>
                                        <th>Total:</th>
                                        <td>{{ $products ? format_currency($products['total'],2,'$'):0 }}</td>
                                    </tr>
                                </table>
                            </div>

                            <a class="btn btn-app" href="{{ url('admin/order/'.$order_id.'/view') }}">
                                <i class="fas fa-shopping-cart"></i> View
                            </a>
                            <a class="btn btn-app" href="javascript:delete_post('{{$order_id}}','detele_order');">
                                <i class="fas fa-trash"></i> Delete
                            </a>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <div class="form-group">
                                <a href="{{ route('admin.orders') }}" class="btn btn-outline-info btn-flat"><i
                                            class="fas fa-chevron-circle-left"></i> Cancel</a>
                                <a href="javascript:save_order()" id="button-save-order"
                                   class="btn btn-outline-info btn-flat float-right"><i
                                            class="fa fa-save fa-right-5"></i> Save <span class="d-none">
                                <i class="fas fa-spinner fa-spin"></i>
                            </span></a>
                            </div>

                        </div>
                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/order/view-order.blade.php
@extends('admin.order.order_layout')
@section('content')
    <?php
    $order =  App\Orders::get_order($order_id);
    $order_status = App\Orders::order_status();
    $payment_type = App\Orders::payment_type();

    $customer_bill = App\Orders::get_meta_product_order($order_id,'customer_bill');
    $billing_address = App\Orders::get_meta_product_order($order_id,'billing_address');
    $customer_shipping = App\Orders::get_meta_product_order($order_id,'customer_shipping');
    $shipping_address = App\Orders::get_meta_product_order($order_id,'shipping_address');
    $products = App\Orders::get_meta_product_order($order_id,'products');
    if(isset($products)){
        $products = display_product_in_order( json_decode($products) );
        $products['tax'] = ($products['subtotal']*$order->tax)/100;
        $products['total'] = $order->shipping + $products['tax'] + $products['subtotal'];
    }
    ?>
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{{ route('admin.orders') }}">Order</a></li>
                        <li class="breadcrumb-item active">Orders Detail</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <!-- Main content -->
                    <div class="invoice p-3 mb-3">
                        <!-- title row -->
                        <div class="row">
                            <div class="col-12">
                                <h4>
                                    <i class="fas fa-globe"></i> KindWard.Com
                                    <small class="float-right">Date: {{ date('m/d/Y') }}</small>
                                </h4>
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- info row -->
                        <div class="row invoice-info">
                            <div class="col-sm-4 invoice-col">
                                Billing Address
                                <address>
                                    <strong>{{  $customer_bill }}</strong><br>
                                    {!! nl2br($billing_address) !!}
                                </address>
                            </div>
                            <!-- /.col -->
                            <div class="col-sm-4 invoice-col">
                                Shipping Address
                                <address>
                                    <strong>{{ $customer_shipping }}</strong><br>
                                    {!! nl2br($shipping_address) !!}
                                </address>
                            </div>
                            <!-- /.col -->
                            <div class="col-sm-4 invoice-col">
                                <b>Order ID #{{ $order_id }}</b><br>
                                <br>
                                <b>Payment type:</b> {{ $payment_type[$order->payment_type]  }}<br>
                                <b>Order Status:</b> {{ $order_status[$order->status] }}<br>
                                <b>Created:</b> {{ $order->created_at }}
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->

                        <!-- Table row -->
                        <div class="row">
                            <div class="col-12 table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>Qty</th>
                                        <th>Product</th>
                                        <th>Attributes</th>
                                        <th>Subtotal</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @if(isset($products))
                                        {!! $products['html']  !!}
                                    @endif
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->

                        <div class="row">
                            <!-- accepted payments column -->
                            <div class="col-6">
                                <p class="lead">Payment Methods:</p>
                                <img src="{{ url('admink/dist/img/credit/visa.png') }}" alt="Visa">
                                <img src="{{ url('admink/dist/img/credit/mastercard.png') }}" alt="Mastercard">
                                <img src="{{ url('admink/dist/img/credit/american-express.png') }}" alt="American Express">
                                <img src="{{ url('admink/dist/img/credit/paypal2.png') }}" alt="Paypal">

                                <p class="text-muted well well-sm shadow-none" style="margin-top: 10px;">
                                    Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles, weebly ning heekya handango imeem
                                    plugg
                                    dopplr jibjab, movity jajah plickers sifteo edmodo ifttt zimbra.
                                </p>
                            </div>
                            <!-- /.col -->
                            <div class="col-6">
                                <p class="lead">Amount Due {{ date('m/d/Y') }}</p>

                                <div class="table-responsive">
                                    <table class="table">
                                        <tr>
                                            <th style="width:50%">Subtotal:</th>
                                            <td>$250.30</td>
                                        </tr>
                                        <tr>
                                            <th>Tax ({{ $order->tax.'%' }})</th>
                                            <td>{{ $order->tax ? format_currency($order->tax * $order->total,2,'$') : '0' }}</td>
                                        </tr>
                                        <tr>
                                            <th>Shipping:</th>
                                            <td>{{ $order->shipping ? format_currency($order->shipping,2,'$') : '0' }}</td>
                                        </tr>
                                        <tr>
                                            <th>Total:</th>
                                            <td>{{ format_currency($order->total,2,'$') }}</td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->

                        <!-- this row will not appear when printing -->
                        <div class="row no-print">
                            <div class="col-12">
                                <a href="javascript:window.print()" class="btn btn-default"><i class="fas fa-print"></i> Print</a>
                                <a href="{{ url('admin/order/'.$order_id.'/edit') }}" class="btn btn-default float-right"><i class="far fa-edit"></i> Edit</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection