routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.frontpage',['slug'=>'/']);
});
Auth::routes();
Route::get('/admin', function(){
    return view('admin.dashboard');
})->name('admin')->middleware('auth')->middleware(['role:administrator']);
Route::get('/home', function(){
    return view('home');
});
//Login
Route::post('loginsite','HomeController@check');

//Group admin
Route::group(['prefix' => 'admin','as'=>'admin.','middleware' => ['auth','role:administrator']], function () {

//    Display users
    Route::get('users', function () {
        $roles = App\User::get_roles();
        return view('admin.users.users',['roles'=>$roles]);
    })->name('users');

//    Display profile user
    Route::get('profile', function () {
        $roles = App\User::get_roles();
        return view('admin.users.profile',['roles'=>$roles]);
    })->name('profile');

    //    Display profile user other
    Route::get('user/{id}/view', function ($id) {
        $roles = App\User::get_roles();
        $user = App\User::getUserByID($id);
        return view('admin.users.user_view',['user'=>$user,'roles'=>$roles]);
    })->name('user_view');

    //    Edit profile user other
    Route::get('user/{id}/edit', function ($id) {
        return view('admin.users.user_edit',['user_id'=>$id]);
    })->name('user_edit');
// change passord
    Route::post('change_password', 'auth\UpdateUser@ChangePassword');
    // update field main user
    Route::post('update_userinfo', 'auth\UpdateUser@UpdateUserInfo');
    // ajax delete user
    Route::post('detele_user', 'auth\UpdateUser@DeleteUser');

    // Posts
    Route::get('posts', function () {
        return view('admin.posts.posts');
    })->name('posts');
    // add new story
    Route::get('add-post', function () {
        return view('admin.posts.addnew_post');
    })->name('add-post');

    // edit story
    Route::get('post/{id}/edit', function ($id) {
        return view('admin.posts.edit_post',['post_id'=>$id]);
    })->name('edit_post');
    // add story
    Route::post('add_post', 'ControllerPosts@add_post');
    //save story
    Route::post('save_post', 'ControllerPosts@save_post');

    // ajax story & all
    Route::post('admin_ajax', 'ControllerAjax@admin_ajax');

    // Media
    Route::get('media', function () {
        return view('admin.media.media');
    })->name('media');
    
    Route::get('media/list', function () {
        return view('admin.media.media_list');
    })->name('media_list');

    Route::post('upload','ControllerMedia@doUpload');

    //products
    Route::get('products', function () {
        return view('admin.products.products');
    })->name('products');

    // product categories
    Route::get('product_categories', function () {
        return view('admin.products.product_categories');
    })->name('product_categories');
    // add product categories
    Route::POST('add_product_category', 'ControllerProduct@add_product_category');

    // add new product
    Route::get('add-product', function () {
        return view('admin.products.add-product');
    })->name('add-product');

    Route::post('add_product','ControllerProduct@add_product');

    // edit product
    Route::get('product/{id}/edit', function ($id) {
        return view('admin.products.edit-product',['product_id'=>$id]);
    })->name('edit-product');

    Route::post('edit_product','ControllerProduct@save_product');

    //Orders
    Route::get('orders', function () {
        return view('admin.order.orders');
    })->name('orders');

    // edit product
    Route::get('order/{id}/view', function ($id) {
        return view('admin.order.view-order',['order_id'=>$id]);
    })->name('view-order');

    // edit new orders
    Route::get('order/{id}/edit', function ($id) {
        return view('admin.order.edit-order',['order_id'=>$id]);
    })->name('edit-order');
    // edit order
    Route::post('edit_order','ControllerOrders@save_order');

    // FAQ setting

    // edit new orders
    Route::get('faq', function () {
        return view('admin.widgets.faq');
    })->name('faq');
    // update FAQ
    Route::post('save_faq','ControllerOptions@save_faq');

    // Contact Form
    Route::get('contact-form', function () {
        return view('admin.widgets.contact-form');
    })->name('contact-form');

    Route::get('contact-form/{slug}', function ($slug) {
        return view('admin.widgets.ctf-detail',['slug'=>$slug]);
    })->name('contact-form-detail');


    // Data Form
    Route::get('data-form', function () {
        return view('admin.maketing.data-form');
    })->name('data-form');

    // add data form
    Route::get('add-data-form', function () {
        return view('admin.maketing.add_data-form');
    })->name('add-data-form');

    // edit data form
    Route::get('data-form/{id}/edit', function ($id) {
        return view('admin.maketing.edit_data-form',['id'=>$id]);
    })->name('edit-data-form');



    // System Settings
    Route::get('system-settings', function () {
        return view('admin.system-settings');
    })->name('system-settings');
});


// main pages
// Stories page
Route::get('/posts', function(){
    return view('frontend.posts',['slug'=>'posts']);
});

// Story detail
Route::get('/post/{slug}', function($slug){
    return view('frontend.single-post',['slug'=>$slug]);
});

//Add story comments
Route::post('/post/{slug}','ControllerStories@add_post_comment');

// Media page
Route::get('/media', function(){
    return view('frontend.media',['slug'=>'media']);
});

// FAQ page
Route::get('/faq', function(){
    return view('frontend.faq',['slug'=>'faq']);
});

// About page
Route::get('/about', function(){
    return view('frontend.about',['slug'=>'about']);
});

// Shop page
Route::get('/gift-shop', function(){
    return view('frontend.shop',['slug'=>'gift-shop']);
})->name('shops');

// Story detail
Route::get('/product/{slug}', function($slug){
    return view('frontend.single-product',['slug'=>$slug]);
});


// My account
Route::get('/my-account', function(){
    return view('frontend.account',['slug'=>'account']);
})->name('my-account')->middleware('auth');

// ajax not admin all
Route::post('nopriv_ajax', 'ControllerAjax@admin_ajax')->name('nopriv_ajax')->middleware('auth');
Route::post('nopriv_upload','ControllerMedia@doUpload')->name('nopriv_ajax')->middleware('auth');


// My cart
Route::get('/cart', function(){
    return view('frontend.cart',['slug'=>'cart']);
})->name('cart');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;

use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','username','level',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public static function get_all_users($level='subcribe'){
        if($level=='administrator' || $level=='super-admin' ){
            $users = DB::table('users')->get();
        }else{
            $users = DB::table('users')->where('level', '=', 'subcribe')->get();
        }

        return $users;
    }

    public static function get_roles(){
        $roles= [
            'subscribe' => 'Subscribe',
            'administrator' => 'Administrator'
        ];
      return $roles;
    }


    public static function getUserByID($id){
        $user = User::where('id',$id)->first();
        return $user;
    }
    public static function update_user($id,$data){
        DB::table('users')
            ->where('id', $id)
            ->update($data);
    }

    // get meta product
    public static function get_user_meta($user_id,$meta_key,$re=''){
        $user_meta = DB::table('user_meta')->where('user_id',$user_id)->where('meta_key',$meta_key)->first();
        if($user_meta)return $user_meta->meta_value ;
        return $re;
    }
    // update meta product
    public static function update_user_meta($user_id,$meta_key,$meta_value){
        $user_meta = self::get_user_meta($user_id,$meta_key);
        if($user_meta){
            DB::table('user_meta')->where('user_id',$user_id)->where('meta_key',$meta_key)->update(['meta_value'=>$meta_value]);
        }else{
            $user_meta =  self::add_user_meta($user_id,$meta_key,$meta_value);
        }
        return $user_meta;
    }

    // get meta product
    public static function add_user_meta($user_id,$meta_key,$meta_value){
        $user_meta = self::get_user_meta($user_id,$meta_key);
        if(!$user_meta){
            $data = array(
                'user_id' => $user_id,
                'meta_key' => $meta_key,
                'meta_value' => $meta_value,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            );
            $meta_id = DB::table('user_meta')->insertGetId($data);
            return $meta_id;
        }
        return false;
    }

}

resources/views/admin/users/user_edit.blade.php
@extends('admin.users.user_layout')
@section('content')
    <?php
    $roles = App\User::get_roles();
    $user = App\User::getUserByID($user_id ?? '');
    ?>
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit Profile: {{ ($user)?$user->name:'' }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.users') }}">Users</a></li>
                        <li class="breadcrumb-item active">Edit Profile</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                {{--colume left--}}
                <div class="col-md-6">
                    <!-- general form elements -->
                    {{--update info--}}
                    <div class="card card-info">
                        <div class="card-header">
                            <h3 class="card-title">Info</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="post" action="{{url('admin/update_userinfo')}}">
                            {{ csrf_field()}}
                            <div class="card-body">
                                <div class="form-group">
                                    @if($errors -> all() && isset($request->action)&& $request->action == 'info')
                                        @foreach($errors->all() as $error)
                                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                                {{$error}}
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                        @endforeach
                                    @endif

                                    @if (Session::has('success_info'))
                                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                                            {{Session::get('success_info')}}
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" class="form-control" name="name" placeholder="Name" value="{{ (isset($request->name))?$request->name:$user->name  }}">
                                </div>
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" class="form-control" name="email" placeholder="Email" value="{{ (isset($request->email))?$request->email:$user->email  }}">
                                </div>
                                <div class="form-group">
                                    <label>Role</label>
                                    <select class="form-control" name="level">
                                        @if( isset($roles))
                                            @foreach($roles as $key => $value)
                                                <option value="{{ $key }}" {{ $key == $user->level ?'selected':'' }}>{{ $value }}</option>
                                            @endforeach
                                        @endif
                                    </select>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <input type="hidden" name="user_id" value="{{ ($user)?$user->id:''}}">
                                <input type="hidden" name="action" value="info">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>
                {{--colume right--}}
                <div class="col-md-6">
                    {{--Update password--}}
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Change password</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="post" action="{{url('admin/change_password')}}">
                            {{ csrf_field()}}
                            <div class="card-body">
                                <div class="form-group">
                                    @if($errors -> all() && isset($request->action) && $request->action == 'change_password')
                                        @foreach($errors->all() as $error)
                                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                                {{$error}}
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                        @endforeach
                                    @endif

                                    @if (Session::has('success_password'))
                                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                                            {{Session::get('success_password')}}
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Password</label>
                                    <input type="password" class="form-control" name="password" placeholder="Password" value="{{ (isset($request))?$request->password:''  }}">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Password Confirm</label>
                                    <input type="password" class="form-control" name="password_comfirm" placeholder="Password Comfirm" value="{{ (isset($request))?$request->password_comfirm:''  }}">
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <input type="hidden" name="user_id" value="{{ ($user)?$user->id:''}}">
                                <input type="hidden" name="action" value="change_password">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/users/user_layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>KindWard | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('admink/plugins/fontawesome-free/css/all.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('admink/dist/css/adminlte.min.css') }}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    @include('admin.sidebar_admin')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        @yield('content')
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.0.5
        </div>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- sweetalert -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<!-- jQuery -->
<script src="{{ asset('admink/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('admink/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('admink/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('admink/dist/js/demo.js')  }}"></script>
<script>
function delete_user(id){
    Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
    }).then((result) => {
        if (result.value) {
            jQuery.ajax({
                url:'{{ url('admin/detele_user/') }}',
                type: 'post',
                data:{action:'detele_user',_token:'{{ csrf_token() }}',user_id:id},
                success: function(resulf){
                    console.log(resulf);
                    if(resulf){
                        document.getElementById("item-user-"+resulf).remove();
                        Swal.fire(
                            'Deleted!',
                            'Your User has been deleted.',
                            'success'
                        )
                    }
                }
            });

        }
    })
}
</script>
</body>

</html>

resources/views/admin/users/users.blade.php
@extends('admin.users.user_layout')
@section('content')
    <?php
    $level = Auth::user()->level;
    $users = App\User::get_all_users($level);
    ?>
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Manage Users</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Manage Users</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Users</h3>

                    <div class="card-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0" style="height: 300px;">
                    <table class="table table-head-fixed text-nowrap table-hover">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>User</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Date</th>
                            <th>Role</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if($users) @foreach($users as $user )
                        <tr id="{{ 'item-user-'.$user->id}}">
                            <td>{{$user->id}}</td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->username}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{ date('Y-m-d', strtotime($user->created_at)) }}</td>
                            <td><span class="tag tag-success">{{$roles[$user->level]}}</span></td>
                            <td class="project-actions ">
                                <a class="btn btn-primary btn-sm" href="{{ route('admin.user_view',['id'=>$user->id] ) }}">
                                    <i class="fas fa-folder">
                                    </i>
                                    View
                                </a>
                                <a class="btn btn-info btn-sm" href="{{ route('admin.user_edit',['id'=>$user->id] ) }}">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Edit
                                </a>
                                <a class="btn btn-danger btn-sm" href="javascript:delete_user({{$user->id}});">
                                    <i class="fas fa-trash">
                                    </i>
                                    Delete
                                </a>
                            </td>
                        </tr>
                        @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
        </div>
    </section>
@endsection