routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.frontpage',['slug'=>'/']);
});
Auth::routes();
Route::get('/admin', function(){
    return view('admin.dashboard');
})->name('admin')->middleware('auth')->middleware(['role:administrator']);
Route::get('/home', function(){
    return view('home');
});
//Login
Route::post('loginsite','HomeController@check');

//Group admin
Route::group(['prefix' => 'admin','as'=>'admin.','middleware' => ['auth','role:administrator']], function () {

//    Display users
    Route::get('users', function () {
        $roles = App\User::get_roles();
        return view('admin.users.users',['roles'=>$roles]);
    })->name('users');

//    Display profile user
    Route::get('profile', function () {
        $roles = App\User::get_roles();
        return view('admin.users.profile',['roles'=>$roles]);
    })->name('profile');

    //    Display profile user other
    Route::get('user/{id}/view', function ($id) {
        $roles = App\User::get_roles();
        $user = App\User::getUserByID($id);
        return view('admin.users.user_view',['user'=>$user,'roles'=>$roles]);
    })->name('user_view');

    //    Edit profile user other
    Route::get('user/{id}/edit', function ($id) {
        return view('admin.users.user_edit',['user_id'=>$id]);
    })->name('user_edit');
// change passord
    Route::post('change_password', 'auth\UpdateUser@ChangePassword');
    // update field main user
    Route::post('update_userinfo', 'auth\UpdateUser@UpdateUserInfo');
    // ajax delete user
    Route::post('detele_user', 'auth\UpdateUser@DeleteUser');

    // Posts
    Route::get('posts', function () {
        return view('admin.posts.posts');
    })->name('posts');
    // add new story
    Route::get('add-post', function () {
        return view('admin.posts.addnew_post');
    })->name('add-post');

    // edit story
    Route::get('post/{id}/edit', function ($id) {
        return view('admin.posts.edit_post',['post_id'=>$id]);
    })->name('edit_post');
    // add story
    Route::post('add_post', 'ControllerPosts@add_post');
    //save story
    Route::post('save_post', 'ControllerPosts@save_post');

    // ajax story & all
    Route::post('admin_ajax', 'ControllerAjax@admin_ajax');

    // Media
    Route::get('media', function () {
        return view('admin.media.media');
    })->name('media');
    
    Route::get('media/list', function () {
        return view('admin.media.media_list');
    })->name('media_list');

    Route::post('upload','ControllerMedia@doUpload');

    //products
    Route::get('products', function () {
        return view('admin.products.products');
    })->name('products');

    // product categories
    Route::get('product_categories', function () {
        return view('admin.products.product_categories');
    })->name('product_categories');
    // add product categories
    Route::POST('add_product_category', 'ControllerProduct@add_product_category');

    // add new product
    Route::get('add-product', function () {
        return view('admin.products.add-product');
    })->name('add-product');

    Route::post('add_product','ControllerProduct@add_product');

    // edit product
    Route::get('product/{id}/edit', function ($id) {
        return view('admin.products.edit-product',['product_id'=>$id]);
    })->name('edit-product');

    Route::post('edit_product','ControllerProduct@save_product');

    //Orders
    Route::get('orders', function () {
        return view('admin.order.orders');
    })->name('orders');

    // edit product
    Route::get('order/{id}/view', function ($id) {
        return view('admin.order.view-order',['order_id'=>$id]);
    })->name('view-order');

    // edit new orders
    Route::get('order/{id}/edit', function ($id) {
        return view('admin.order.edit-order',['order_id'=>$id]);
    })->name('edit-order');
    // edit order
    Route::post('edit_order','ControllerOrders@save_order');

    // FAQ setting

    // edit new orders
    Route::get('faq', function () {
        return view('admin.widgets.faq');
    })->name('faq');
    // update FAQ
    Route::post('save_faq','ControllerOptions@save_faq');

    // Contact Form
    Route::get('contact-form', function () {
        return view('admin.widgets.contact-form');
    })->name('contact-form');

    Route::get('contact-form/{slug}', function ($slug) {
        return view('admin.widgets.ctf-detail',['slug'=>$slug]);
    })->name('contact-form-detail');


    // Data Form
    Route::get('data-form', function () {
        return view('admin.maketing.data-form');
    })->name('data-form');

    // add data form
    Route::get('add-data-form', function () {
        return view('admin.maketing.add_data-form');
    })->name('add-data-form');

    // edit data form
    Route::get('data-form/{id}/edit', function ($id) {
        return view('admin.maketing.edit_data-form',['id'=>$id]);
    })->name('edit-data-form');



    // System Settings
    Route::get('system-settings', function () {
        return view('admin.system-settings');
    })->name('system-settings');
});


// main pages
// Stories page
Route::get('/posts', function(){
    return view('frontend.posts',['slug'=>'posts']);
});

// Story detail
Route::get('/post/{slug}', function($slug){
    return view('frontend.single-post',['slug'=>$slug]);
});

//Add story comments
Route::post('/post/{slug}','ControllerStories@add_post_comment');

// Media page
Route::get('/media', function(){
    return view('frontend.media',['slug'=>'media']);
});

// FAQ page
Route::get('/faq', function(){
    return view('frontend.faq',['slug'=>'faq']);
});

// About page
Route::get('/about', function(){
    return view('frontend.about',['slug'=>'about']);
});

// Shop page
Route::get('/gift-shop', function(){
    return view('frontend.shop',['slug'=>'gift-shop']);
})->name('shops');

// Story detail
Route::get('/product/{slug}', function($slug){
    return view('frontend.single-product',['slug'=>$slug]);
});


// My account
Route::get('/my-account', function(){
    return view('frontend.account',['slug'=>'account']);
})->name('my-account')->middleware('auth');

// ajax not admin all
Route::post('nopriv_ajax', 'ControllerAjax@admin_ajax')->name('nopriv_ajax')->middleware('auth');
Route::post('nopriv_upload','ControllerMedia@doUpload')->name('nopriv_ajax')->middleware('auth');


// My cart
Route::get('/cart', function(){
    return view('frontend.cart',['slug'=>'cart']);
})->name('cart');

app/Posts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Posts extends Model
{
    protected $table = 'posts';
    public static function get_posts($where=''){
        $posts = DB::table('posts')->paginate(10);
        return $posts;
    }
    /// query story
    public static function query_stories($where=array(),$orderby='created_at', $order='desc',$limit=10,$paginate=10){
        $stories = DB::table('posts')->where('status',1);
        if(isset($where)){
            foreach ($where as $key => $value){
                $stories->where($value['name'],$value['operator'],$value['value']);
            }
        }
        $stories->orderBy($orderby,$order);
        if($limit)$stories->limit($limit);
        $resulf = $stories->paginate($paginate);
        return $resulf;
    }
    public static function post_category(){
        $post_cateroty = [
            0 => 'General',
            1 => 'Lifestyle',
            2 => 'People',
            3 => 'Places',
        ];
        return $post_cateroty;
    }
// status stories
    public static function post_status(){
        $post_status = [
            0 => 'Draft',
            1 => 'Published',
            2 => 'Hidden',
            3 => 'Deleted',
        ];
        return $post_status;
    }
    // type of stories
    public static function post_types(){
        $post_types = [
            0 => 'Post',
            1 => 'Media',
        ];
        return $post_types;
    }

    // get story by slug
    public static function get_post_by_slug($slug=''){
        $post = DB::table('posts')->where('slug',$slug)->first();
        return $post;
    }

    // get story by id
    public static function get_post($post_id){
        $post = DB::table('posts')->where('id',$post_id)->first();
        return $post;
    }

    public function DeletePost($id)
    {
        DB::table('posts')->where('id',$id)->delete();
    }
    // get comment story
    public static function get_comment_post($post_id){
        $posts_comments = DB::table('posts_comment')->where('post_id',$post_id)->orderByDesc('created_at')->paginate(10);
        return $posts_comments;
    }

    // get comment story
    public static function get_comment_post_publish($story_id){
        $post_comments = DB::table('posts_comment')->where('post_id',$story_id)->where('status',1)->orderByDesc('created_at')->paginate(10);
        return $post_comments;
    }
    // get status comment
    public static function comment_status(){
        $comment_status = [
            0 => 'Pending',
            1 => 'Active',
            2 => 'Spam',
        ];
        return $comment_status;
    }

    // get meta story
    public static function get_meta_post($post_id,$meta_key,$re=''){
        $post = DB::table('meta_post')->where('post_id',$post_id)->where('meta_key',$meta_key)->first();
        if($post)return $post ;
        return $re;
    }
    // update meta story
    public static function update_meta_post($post_id,$meta_key,$meta_value){
        $post = DB::table('meta_post')->where('post_id',$post_id)->where('meta_key',$meta_key)->update(['meta_value'=>$meta_value]);
        return $post;
    }

    // get meta story
    public static function add_meta_post($post_id,$meta_key,$meta_value){
        $post = self::get_meta_story($post_id,$meta_key);
        if(!$post){
            $data = array(
                'story_id' => $post_id,
                'meta_key' => $meta_key,
                'meta_value' => $meta_value,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            );
            $post_id = DB::table('meta_story')->insertGetId($data);
            return $post_id;
        }
        return false;
    }

    public static function get_categories_post(){
        $categories = DB::table('posts')->select(DB::raw('post_category,count(*) as number'))->groupBy('post_category')->get();
        return $categories;
    }

    public static function add_post_comment($data){
        $data['status'] = 0;
        $data['created_at'] = date('Y-m-d H:i:s');
        $data['updated_at'] = date('Y-m-d H:i:s');
        unset($data['action']);
        unset($data['slug']);
        unset($data['_token']);
        $post_comment =  DB::table('posts_comment')->insertGetId($data);
        return $post_comment;
    }


}

resources/views/admin/posts/addnew_post.blade.php
@extends('admin.posts.post_layout')
@section('content')
    <?php
    $user = Auth::user();
    $post_cateroty = App\Posts::post_category();
    $post_status = App\Posts::post_status();
    $post_types = App\Posts::post_types();
    $medias = App\Media::get_media();
    ?>
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add new post</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.posts') }}">Posts</a></li>
                        <li class="breadcrumb-item active">Add new post</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                {{--colume left--}}
                <div class="col-md-9">
                    <!-- general form elements -->
                    {{--update info--}}
                    <div class="card card-info">
                        <div class="card-header">
                            <h3 class="card-title">Post Information</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form class="form-horizontal create_new_story" name="frmAdd" method="post" enctype="multipart/form-data" role="form">
                            <div class="card-body">
                                <!--Title-->
                                <div class="form-group">
                                    <label for="story_title" class="control-label">Post Title</label>
                                    <input type="text" class="form-control" id="post_title" name="post_title" placeholder="Post Title" value="" data-title="Post Title" data-required="true" />
                                    <span class="um-field-error d-none"></span>
                                </div>
                                <!--Content-->
                                <div class="form-group">
                                    <label for="story_content" class="control-label">Post Content</label>
                                    <textarea id="post_content" name="post_content" class="form-control summernote editor_summernote" rows="10" placeholder="Post content..." data-title="Content" data-required="false"></textarea>
                                    <span class="um-field-error d-none"></span>
                                </div>
                                <!--Category-->
                                <div class="form-group">
                                    <label for="story_category" class="control-label">Category</label>
                                    <select class="form-control" name="post_category" id="post_category" data-title="Category" data-required="true">

                                        @if (!empty($post_cateroty))
                                            @foreach ($post_cateroty as $key=> $value)


                                                <option value="{{ $key }}">{{ $value }}</option>

                                            @endforeach
                                        @endif

                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="status" class="control-label">Status</label>
                                    <select class="form-control" id="status" name="status" data-title="Status" data-required="true">

                                        @foreach ($post_status as $key => $val)
                                            <option value="{{ $key }}">{{ $val }}</option>
                                        @endforeach
                                    </select>
                                </div>


                                <div class="form-group">
                                    <label for="story_notes" class="control-label">Internal Notes</label>
                                    <textarea id="post_notes" name="post_notes" class="form-control" rows="3" placeholder="Internal notes..." data-title="Notes" data-required="false"></textarea>
                                </div>
                                <div class="form-group">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}" data-title="Token" data-required="false">
                                    <input type="hidden" id="action" name="action" value="{{ url('admin/add_post/') }}" data-title="action" data-required="false" />
                                    <input type="hidden" id="user_id" name="user_id" value="<?php echo $user->id?>" data-title="User" data-required="false" />
                                </div>
                            </div>


                        </form>
                    </div>
                    <!-- /.card -->
                </div>
                {{--colume right--}}
                <div class="col-md-3">
                    <!-- general form controls -->
                    <div class="card card-info">
                        <div class="card-header">
                            <h3 class="card-title">Control</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <a href="{{ route('admin.posts') }}" class="btn btn-outline-info btn-flat"><i class="fas fa-chevron-circle-left"></i> Cancel</a>
                            <a href="javascript:save_post()" id="button-save-story"  class="btn btn-outline-info btn-flat float-right"><i class="fa fa-save fa-right-5"></i> Save <span class="d-none">
                                <i class="fas fa-spinner fa-spin"></i>
                            </span></a>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                    <!--Story type-->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Post type</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                            <div class="card-body">
                                <div class="form-group create_new_story">
                                    <label for="status" class="control-label">Type</label>
                                    <select class="form-control" id="post_type" name="post_type" data-title="Type" data-required="false">
                                        @foreach ($post_types as $key => $val)
                                            <option value="{{ $key }}">{{ $val }}</option>
                                        @endforeach
                                    </select>
                                    <span class="um-field-error d-none"></span>
                                </div>
                                <div id="show-media" class="form-group d-none">
                                    <div class="display-media">

                                    </div>
                                    <!-- Button trigger modal -->
                                    <div type="button" class="btn btn-primary button_upload_media" data-media="audio" data-ftype="audio" data-type="audio/mp3" data-toggle="modal" data-target="#MediaModal" data-required=true>
                                        Upload Audio
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->
                    </div>
                    {{--Story Image--}}
                    <div class="card card-primary">
                        <!-- /.card-header -->
                        <div class="card-header">
                            <h3 class="card-title">Post Image</h3>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-body">
                            <div id="show-images" class="form-group">
                                <div class="display-media">

                                </div>
                                <!-- Button trigger modal -->
                                <div type="button" class="btn btn-primary button_upload_media" data-media="button_featured_image" data-ftype="image" data-type="image/*" data-toggle="modal" data-target="#MediaModal" data-required="false">
                                    Upload image
                                </div>
                            </div>
                        </div>
                        <!-- form start -->

                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/posts/posts.blade.php
@extends('admin.posts.post_layout')
@section('content')
    <?php
    $posts =  App\Posts::get_posts();
    $Status =  App\Posts::post_status();
    $Category =  App\Posts::post_category();
    $post_types = App\Posts::post_types();
    ?>
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1><a href="{{ route('admin.add-post') }}" class="btn btn-outline-info">Add new</a></h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Manage Posts</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Posts ({{ $posts->total() }})</h3>

                            <div class="card-tools">
                                <div class="input-group input-group-sm" style="width: 150px;">
                                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0">
                            <table class="table table-head-fixed text-nowrap table-hover">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Category</th>
                                    <th>User</th>
                                    <th>Type</th>
                                    <th>Status</th>
                                    <th>Last Modified</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if (count($posts) > 0)
                                @foreach ($posts as $post)
                                <tr>
                                    <td><?php echo $post->id ?></td>
                                    <td><?php echo $post->post_title?></td>
                                    <td>{{ $Category[$post->post_category]}}</td>
                                    <td>{{ App\User::getUserByID($post->user_id)->name }}</td>
                                    <td>{{ $post_types[$post->post_type] }}</td>
                                    <td>{{ $Status[$post->status]}}</td>
                                    <td>{{$post->updated_at}}</td>
                                    <td>
                                        <a class="btn btn-primary btn-sm" href="#">
                                            <i class="fas fa-folder">
                                            </i>
                                            View
                                        </a>
                                        <a class="btn btn-info btn-sm" href="{{ route('admin.edit_post',['id'=>$post->id]) }}">
                                            <i class="fas fa-pencil-alt">
                                            </i>
                                            Edit
                                        </a>
                                        <a class="btn btn-danger btn-sm" href="javascript:delete_post('{{$post->id}}','detele_story');">
                                            <i class="fas fa-trash">
                                            </i>
                                            Delete
                                        </a>
                                    </td>
                                </tr>
                                @endforeach
                                @else
                                <tr>
                                    <td colspan="8" class="text-center">No stores exist.</td>
                                </tr>
                                @endif

                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            <li class="page-item"><a class="page-link" href="{{ $posts->previousPageUrl() }}">Previous</a></li>
                            <li class="page-item"><span class="page-link">{{ $posts->currentPage() }}</span></li>
                            <li class="page-item"><a class="page-link" href="{{ $posts->nextPageUrl() }}">Next</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </section>
@endsection